# PostgreSQL Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13.1
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: test32!
          - name: POSTGRES_USER
            value: reviewvideo
          - name: POSTGRES_DB
            value: reviewvideo
---

#Service PostgreSQL
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
  type: ClusterIP

---
# Application Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviewvideo
spec:
  selector:
    matchLabels:
      app: reviewvideo
  template:
    metadata:
      labels:
        app: reviewvideo
    spec:
      containers:
      - name: reviewvideo
        image: weddly/devops4dev-review-movies:v1
        ports:
        - containerPort: 8080
        env:
          - name: ASPNETCORE_HTTP_PORTS
            value: "8080"
          - name: ConnectionStrings__DefaultConnection
            value: "Host=postgres;Database=reviewvideo;Username=reviewvideo;Password=test32!"
---
apiVersion: v1
kind: Service
metadata:
  name: reviewvideo
spec:
  selector:
    app: reviewvideo
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
  externalIPs:
    - 10.10.10.10
